default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: hieu12345
  #socket: /tmp/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: anime-development

test:
  <<: *default
  database: anime-test

production:
  <<: *default
  database: anime-development
  username: anime-test
  password: <%= ENV['RUBY-HT-BOOK-REVIEW-SYSTEM_DATABASE_PASSWORD'] %>
