User.create!(email: "hieu@gmail.com",
  password: "123123", password_confirmation: "123123", admin: true)
Category.create!(name: "Siêu nhiên")
Category.create!(name: "Đời thường")
Category.create!(name: "Drama")
Category.create!(name: "Phiêu lưu")
Category.create!(name: "Lịch sử")
Category.create!(name: "Âm nhạc")
Category.create!(name: "Blu-ray")
Category.create!(name: "Game")
Category.create!(name: "Kinh dị")
Category.create!(name: "Học đường")
Category.create!(name: "Hài hước")
Category.create!(name: "Viễn tưởng")
Category.create!(name: "Hành động")
Category.create!(name: "Phép thuật")
Category.create!(name: "Thể thao")
Category.create!(name: "Học đường")
Category.create!(name: "Trinh thám")
Category.create!(name: "Harem")
Category.create!(name: "Lãng mạn")
Category.create!(name: "Ecchi")
